#!/bin/sh
echo "circle"

echo "build images and containers"
docker-compose build web
docker-compose up -d --build web percona

echo "setup magento"
docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm setup
