#!/bin/sh
echo "Initializing setup..."

echo "composer install"
su-exec www-data \
  composer install

echo "dir"

ls -la .

find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
chown -R :www-data .
chmod u+x bin/magento

ls -la vendor

echo "setup"
su-exec www-data \
  php -d memory_limit=2G ./bin/magento setup:install \
    --db-host=$MAGE_SETUP_DB_HOST \
    --db-name=$MAGE_SETUP_DB_NAME \
    --db-user=$MAGE_SETUP_DB_USER \
    --db-password=$MAGE_SETUP_DB_PASSWORD \
    --base-url=$MAGE_SETUP_BASE_URL \
    --backend-frontname=$MAGE_SETUP_ADMIN_BACKEND_FRONTNAME \
    --admin-firstname=$MAGE_SETUP_ADMIN_FIRSTNAME \
    --admin-lastname=$MAGE_SETUP_ADMIN_LASTNAME \
    --admin-email=$MAGE_SETUP_ADMIN_EMAIL \
    --admin-user=$MAGE_SETUP_ADMIN_USER \
    --admin-password=$MAGE_SETUP_ADMIN_PASSWORD

echo "Setup finished..."